create table {SENDTABLE}( 
mseq integer not null generated always as identity(start with 1, increment by 1, no cache), 
msg_type char(1)  not null default '1', 
send_type char(1) not null default '1' , 
dkey varchar(50) not null default '0', 
dcnt decimal(11) not null default 0 , 
dstaddr varchar(20) not null default '0', 
callback varchar(20) null, 
stat char(1) not null default '0', 
subject varchar(120) null, 
text_type char(1)  not null default '0', 
text varchar(4000) not null default ' ', 
text2 varchar(4000) null,
expiretime decimal(8) not null default 86400 , 
filecnt decimal(3) not null default 0, 
fileloc1 varchar(512) null, 
filesize1 decimal(11) null, 
fileloc2 varchar(512) null, 
filesize2 decimal(11) null, 
fileloc3 varchar(512) null, 
filesize3 decimal(11) null, 
fileloc4 varchar(512) null, 
filesize4 decimal(11) null, 
fileloc5 varchar(512) null, 
filesize5 decimal(11) null, 
filecnt_checkup decimal(3) not null default 0, 
insert_time timestamp not null default current timestamp, 
request_time timestamp not null default current timestamp, 
send_time timestamp null, 
report_time timestamp null, 
tcprecv_time timestamp null, 
save_time timestamp null, 
telecom varchar(10) null, 
result char(4) null, 
repcnt decimal(6) not null default 0, 
server_id decimal(11) null, 
opt_id varchar(20) null, 
opt_cmp  varchar(40) null, 
opt_post varchar(40) null, 
opt_name varchar(40) null, 
ext_col0 decimal(10) null, 
ext_col1 varchar(64) null, 
ext_col2 varchar(32) null, 
ext_col3 varchar(32) null,
pseq varchar(10) null,
sender_key varchar(40) null,

k_template_code varchar(30) null,
k_expiretime decimal(6) null default 180,
k_next_type decimal(1) null default 0,

k_at_send_type char(1) default '0',
k_ad_flag char(1) default 'N',

k_attach varchar(4000) null,
k_attach2 varchar(2000) null,

primary key(mseq) 
) in tsp_sms;


